### ISSUE TITLE
Tutorial link is down

### ISSUE THREAD

**Issue by nopara73** [figueiredorui/cross-platform-desktop#1]
Hey, the tutorial link is down. I'm not sure if this is temporary, anyway could you upload it somewhere? 
https://scotch.io/@rui/how-to-build-a-cross-platform-desktop-application-with-electron-and-net-core

**Comment by figueiredorui** [comment]
Hi @nopara73, thanks for reporting the issue. I believe it's online again.
Cheers.

**Comment by nopara73** [comment]
Yes it is.
